export {default as Home} from "./Home"
export {default as Camera} from "./Camera"
export {default as Notifications} from "./Notifications"
export {default as Search} from "./Search"
export {default as Settings} from "./Settings"